### ISSUE TITLE
Need to fix license

### ISSUE THREAD

**Issue by kdpsingh** [drizk1/TidierText.jl#2]
For this (and for the other TidierOrg packages), we need to ensure that our license appropriately acknowledges the contributions of the R packages whose API and functionality we are implementing.

Keeping this here as a note to self. Once we figure out how to address here, let's fix throughout the Tidier ecosystem.

**Comment by kdpsingh** [comment]
Given that we re-implement the tidytext interface (even though we don't directly reuse any code), i think it is a good gesture for us to add the copyright holders for tidytext onto our license. I've gone ahead and made that change in our license, adding David Robinson and Julia Silge.

I'll close this issue. We should discuss making the same change for our other packages.

**Comment by drizk1** [comment]
Thank you so much for doing this. Following suit with the other licenses sounds good to me, but I'm happy with any route.
