### ISSUE TITLE
Add logo

### ISSUE THREAD

**Issue by kdpsingh** [drizk1/TidierText.jl#3]
@pdimens, happy Thanksgiving! After the holidays, if you happen to have the bandwidth to work on a logo for TidierText.jl, would love your help.

If busy, no worries!

**Comment by cormullion** [comment]
Hi! I'm not Pavel, nor have his artistic talent, but I thought it would be fun to try and design one of these in his style!

<img width="783" alt="Screenshot 2023-11-27 at 10 07 05" src="https://github.com/TidierOrg/TidierText.jl/assets/52289/e21ed11c-254e-48f0-a1cc-7f413db5a334">

[tidiertext-logo.svg.zip](https://github.com/TidierOrg/TidierText.jl/files/13472786/tidiertext-logo.svg.zip)

**Comment by kdpsingh** [comment]
I *love* it! @drizk1, any thoughts on your end?

**Comment by drizk1** [comment]
This looks great! I am wondering, would it be possible to use the same, or a similar, sans serif font for the tidier part below? I think that would look super _neat_ .  Thank you!

Edit: courier font could be interesting as an ode to classic typewriter fonts as well?

**Comment by cormullion** [comment]
No problem: using the same font (URW Gothic Demi is the house style I think)

<img width="398" alt="Screenshot 2023-11-27 at 15 40 29" src="https://github.com/TidierOrg/TidierText.jl/assets/52289/018f2ff1-4db5-44d9-8d78-05873ca3b8d8">

**Comment by kdpsingh** [comment]
Love this! If I had to nitpick, the only thing I would consider is to have the back arm of the tweezer to be behind the "e". But this looks great.

**Comment by drizk1** [comment]
One other small thing that I just noticed, would it be possible to have the outlines of the dotted eyes in TidierText be a darker version of the their color (blue green red purple) to match the other Tidier packages? Thank you!

**Comment by cormullion** [comment]
No problems - nit-picking is the Julian way! :) 

<img width="453" alt="Screenshot 2023-11-27 at 18 02 57" src="https://github.com/TidierOrg/TidierText.jl/assets/52289/09176891-f04a-4165-9dce-8d31e7bd4d44">

How are we doing?

**Comment by cormullion** [comment]
here's an SVG:

[tidiertext-logo.svg.zip](https://github.com/TidierOrg/TidierText.jl/files/13478736/tidiertext-logo.svg.zip)

Source code is [here](https://gist.github.com/cormullion/0e502b16e7e0f1607084c206d93e5cc5).

**Comment by drizk1** [comment]
Thank you!

**Comment by kdpsingh** [comment]
Am blown away that you made this with code.

**Comment by kdpsingh** [comment]
@cormullion Thank you so, so much for your creativity and contribution!

Quick question: Do you have an easy way to save the SVG also as a PNG and approximate the resolution used by the other Tidier logos?

If not, we'll figure it out. Just thought I'd ask as you are an expert at this.

(We always keep an SVG copy but use the PNG on GitHub README, etc.)

**Comment by cormullion** [comment]
I use a little macOS app called Gapplin which exports SVG to PNG. There's probably similar apps for other platforms.

Of course, you can save Luxor drawings to PNG/PDF as well. If you tell me the dimensions I can upload a copy...

Thank you for letting me contribute!

**Comment by kdpsingh** [comment]
Much, much appreciated!

Here's an example of one of our other logos: https://github.com/TidierOrg/Tidier.jl/blob/main/docs/src/assets/Tidier_jl_logo.png

I believe the resolution is 1314 x 1475. I'm assuming there's more blank space on one axis than the other, which is why it's not a square. Would just try to approximate this but doesn't have to be exact -- we always fix the dimensions in HTML/CSS when displaying.

**Comment by pdimens** [comment]
Woah, that's awesome. I really like it. My only note is the make the stroke/border around the tweezers a darker version of the beige of the tweezers.

**Comment by pdimens** [comment]
@kdpsingh sorry, I stopped getting emails from GH when I'm tagged. Not sure why. Only saw this today by chance.

**Comment by kdpsingh** [comment]
No worries, @pdimens. Appreciate you weighing in and appreciate @cormullion collab!

**Comment by cormullion** [comment]
png is quite big :) 

![tidiertext-logo](https://github.com/TidierOrg/TidierText.jl/assets/52289/643dcff7-a4c0-48b4-a0d0-84f1a784d62c)

I'm loving your artistic styling here @pdimens - it's not what I'm used to :)

**Comment by drizk1** [comment]
This is incredible !! Thank you again. Last possible request, is it possible to make the green a bit softer to mesh with the other logos. Perhaps having the gradient go to a whitish? Again sorry to mention this late

**Comment by cormullion** [comment]
no problem, will do it tomorrow - food is waiting 😂

**Comment by kdpsingh** [comment]
As an exciting update, as of this today, TidierText is on the Julia registry! Had to do a manual merge bc of name similarity to TidierVest preventing auto-merging.

Will update Tidier.jl soon to include TidierText as part of its packaging.

**Comment by pdimens** [comment]
Ah @cormullion that's amazing! It's stylistically spot on! 🤓

**Comment by cormullion** [comment]
A less contrasty green ...

![tidiertext-logo](https://github.com/TidierOrg/TidierText.jl/assets/52289/0d732077-21ab-44d3-af14-643bd44dc984)

(My eyes tend to prefer more contrasty colours -just an age thing... 🧓🏼 :))

[tidiertext-logo.svg.zip](https://github.com/TidierOrg/TidierText.jl/files/13486633/tidiertext-logo.svg.zip)

**Comment by kdpsingh** [comment]
@cormullion -- looks beautiful!

Once @drizk1 reviews, I'll update the logo throughout.

**Comment by drizk1** [comment]
This looks great! Thank you @cormullion

**Comment by kdpsingh** [comment]
The logo is officially added! Thank you everyone, especially @cormullion!
